draw_config:
  append_colon_to_layer_header: true
  arc_radius: 6.0
  arc_scale: 1.0
  combo_h: 26.0
  combo_w: 28.0
  inner_pad_h: 2.0
  inner_pad_w: 2.0
  key_h: 56.0
  key_rx: 6.0
  key_ry: 6.0
  key_w: 60.0
  line_spacing: 1.2
  outer_pad_h: 56.0
  outer_pad_w: 30.0
  small_pad: 2.0
  split_gap: 30.0
  dark_mode: false
  n_columns: 2
parse_config:
  zmk_additional_includes: ["zmk-helpers/include"]
  assign_combos_to_layers: false
  preprocess: true
  qmk_keycode_map:
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    AT: '@'
    BACKSLASH: \
    BSLS: \
    CIRC: ^
    CIRCUMFLEX: ^
    COLN: ':'
    COLON: ':'
    COMM: ','
    COMMA: ','
    DLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTE: '"'
    DQT: '"'
    DQUO: '"'
    EQL: '='
    EQUAL: '='
    EXCLAIM: '!'
    EXLM: '!'
    GRAVE: '`'
    GRV: '`'
    GT: '>'
    HASH: '#'
    LABK: <
    LBRC: '['
    LCBR: '{'
    LEFT_ANGLE_BRACKET: <
    LEFT_BRACKET: '['
    LEFT_CURLY_BRACE: '{'
    LEFT_PAREN: (
    LPRN: (
    LT: <
    MINS: '-'
    MINUS: '-'
    'NO': ''
    NONUS_HASH: '#'
    NUHS: '#'
    PERC: '%'
    PERCENT: '%'
    PIPE: '|'
    PLUS: +
    QUES: '?'
    QUESTION: '?'
    QUOT: ''''
    QUOTE: ''''
    RABK: '>'
    RBRC: ']'
    RCBR: '}'
    RIGHT_ANGLE_BRACKET: '>'
    RIGHT_BRACKET: ']'
    RIGHT_CURLY_BRACE: '}'
    RIGHT_PAREN: )
    RPRN: )
    SCLN: ;
    SEMICOLON: ;
    SLASH: /
    SLSH: /
    TILD: '~'
    TILDE: '~'
    TRANSPARENT: ''
    TRNS: ''
    UNDERSCORE: _
    UNDS: _
    SPACE: ⎵
  raw_binding_map:
    "&bootloader": { t: Boot, h: $$mdi:progress-download$$ }
    "&caps_word": { t: Caps Word, h: $$mdi:apple-keyboard-caps$$ }
    "&studio_unlock": { t: ZMK Studio, h: $$mdi:lock-open-variant$$ }

    "&kp UP": $$mdi:arrow-up$$
    "&kp DOWN": $$mdi:arrow-down$$
    "&kp LEFT": $$mdi:arrow-left$$
    "&kp RIGHT": $$mdi:arrow-right$$

    "&kp C_STOP": $$mdi:stop$$
    "&kp C_PP": $$mdi:play-pause$$
    "&kp C_PREV": $$mdi:skip-previous$$
    "&kp C_NEXT": $$mdi:skip-next$$
    "&kp C_VOL_DN": $$mdi:volume-minus$$
    "&kp C_VOL_UP": $$mdi:volume-plus$$
    "&kp C_MUTE": $$mdi:volume-mute$$

    "&mmv MOVE_UP": Mouse Up
    "&mmv MOVE_DOWN": Mouse Down
    "&mmv MOVE_LEFT": Mouse Left
    "&mmv MOVE_RIGHT": Mouse Right

    "&msc SCRL_UP": { t: Scroll Up, h: $$mdi:pan-up$$}
    "&msc SCRL_DOWN": { t: Scroll Down, h: $$mdi:pan-down$$}
    "&msc SCRL_LEFT": { t: Scroll Left, h: $$mdi:pan-left$$}
    "&msc SCRL_RIGHT": { t: Scroll Right, h: $$mdi:pan-right$$}

    "&mkp RCLK": Right Click
    "&mkp LCLK": Left Click
    "&mkp MCLK": Middle Click
    "&mkp MB4": { t: Back, h: $$mdi:backburger$$ }
    "&mkp MB5": { t: Forward, h: $$mdi:forwardburger$$ }

    "&kp LG(C)": { t: Copy, h: $$mdi:content-copy$$ }
    "&kp LG(V)": { t: Paste, h: $$mdi:content-paste$$ }
    "&kp LG(X)": { t: Cut, h: $$mdi:content-cut$$ }
    "&kp LG(Z)": { t: Undo, h: $$mdi:undo$$ }
    "&kp LG(LS(Z))": { t: Redo, h: $$mdi:redo$$ }

    "&kp LGUI": { t: LGUI, h: $$mdi:apple-keyboard-command$$ }
    "&kp LALT": { t: LALT, h: $$mdi:apple-keyboard-option$$ }
    "&kp LCTRL": { t: LCTRL, h: $$mdi:apple-keyboard-control$$ }
    "&kp LSHFT": { t: LSHFT, h: $$mdi:apple-keyboard-shift$$ }
    "&kp RGUI": { t: RGUI, h: $$mdi:apple-keyboard-command$$ }
    "&kp RALT": { t: RALT, h: $$mdi:apple-keyboard-option$$ }
    "&kp RCTRL": { t: RCTRL, h: $$mdi:apple-keyboard-control$$ }
    "&kp RSHFT": { t: RSHFT, h: $$mdi:apple-keyboard-shift$$ }
  skip_binding_parsing: false
  zmk_keycode_map:
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: "="
    PLUS: +
    MINUS: "-"
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: \
    BSLH: \
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ;
    SEMI: ;
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ","
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"
  zmk_combos:
    combo_left_mclk: { k: { t: "Mid Clk" } }
    combo_right_mclk: { k: { t: "Mid Clk" } }
  zmk_preamble: "#define KEYMAP_DRAWER"